volume_database:
  image: busybox:latest
  volumes:
    - /var/lib/mysql
  container_name: volume_baseball_database
  tty: true

db:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: your_root_password
    MYSQL_DATABASE: retrosheet
    MYSQL_USER: app_user
    MYSQL_PASSWORD: your_password
  volumes:
    - ./config/mysql:/etc/mysql/conf.d
  volumes_from:
    - volume_database
  ports:
    - "3306:3306"
  container_name: baseball_database_mysql
